---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/app: "keycloak"
      app.kubernetes.io/instance: "base"
      app.kubernetes.io/managed-by: "kustomize"

resources:
  - sa.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - statefulset.yaml
  - service.yaml
  - service-headless.yaml
  - ingress.yaml
  - role.yaml
  - rolebinding.yaml

configMapGenerator:
  - name: keycloak-config
    literals:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_HTTP_PORT=8080
      - KEYCLOAK_PROXY_HEADERS=forwarded|xforwarded
      - KEYCLOAK_ENABLE_STATISTICS=false
      - KEYCLOAK_PRODUCTION=true
      - KC_HTTP_ENABLED=true
      - KC_ENABLE_HTTPS=true
      - KC_HEALTH_ENABLED=true
      - KC_HTTP_MANAGEMENT_PORT=9000
      - KEYCLOAK_HTTPS_PORT=8443
      - KC_HTTPS_CERTIFICATE_FILE=/etc/keycloak-certs/tls.crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/keycloak-certs/tls.key
      - KC_CACHE=ispn
      - KC_CACHE_STACK=kubernetes
      - KEYCLOAK_LOG_OUTPUT=default
      - KC_LOG_LEVEL=DEBUG
      - QUARKUS_TRANSACTION_MANAGER_OBJECT_STORE_DIRECTORY=/tmp
      - KC_LOG_CONSOLE_COLOR=true
      - JAVA_OPTS=
        -XX:+UseContainerSupport
        -Dkubeping_namespace=keycloak
        -Dkubeping_label="keycloak-cluster=default"
      - JAVA_OPTS_KC_HEAP=-XX:MaxHeapFreeRatio=30 -XX:MaxRAMPercentage=74.0
  # - name: keycloak-ispn-config
  #   files:
  #     - config/cache-ispn-kubeping.xml
