---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: infra-kc-keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: keycloak
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: keycloak
