---
apiVersion: v1
kind: Service
metadata:
  name: "keycloak"
spec:
  ports:
    - name: "http"
      port: 8080
      protocol: "TCP"
      targetPort: "http"
    - name: "https"
      port: 8443
      protocol: "TCP"
      targetPort: "https"
  selector:
    app.kubernetes.io/component: "keycloak"
  type: "ClusterIP"
