---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: "zookeeper-config"
    files:
      - scripts/ok
      - scripts/run
      - scripts/ready

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: "zookeeper"
      app.kubernetes.io/version: "3.9.5"
      app.kubernetes.io/part-of: "zuul"

images:
  - name: "zookeeper"
    #newName: "quay.io/opentelekomcloud/zookeeper"
    #newTag: "3.8.1@sha256:bf742c6e9df263e2245d6a8a487c43bf43d9cd1f685caa07ddecd760f3a21950"
    newTag: "3.9.5@sha256:861113a4972110c2258ee3f62807c0eec33235ea3aa3d360da48211ce401e23d"

resources:
  - cert.yaml
  - sa.yaml
  - service.yaml
  - statefulset.yaml
  - pdb.yaml
