---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: "zookeeper-config"
    files:
      - scripts/ok
      - scripts/run
      - scripts/ready

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: "zookeeper"
      app.kubernetes.io/version: "3.8.1"
      app.kubernetes.io/part-of: "zuul"

images:
  - name: "zookeeper"
    #newName: "quay.io/opentelekomcloud/zookeeper"
    newTag: "3.9.2@sha256:b34b773e67cf5139de0688f3e0caf2d0316db763d5dde8b8ee6af0bbd91c720c"

resources:
  - cert.yaml
  - sa.yaml
  - service.yaml
  - statefulset.yaml
  - pdb.yaml
