---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodepool-launcher
  labels:
    app.kubernetes.io/name: "zuul"
    app.kubernetes.io/part-of: zuul
    app.kubernetes.io/component: "nodepool-launcher"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "zuul"
      app.kubernetes.io/part-of: "zuul"
      app.kubernetes.io/component: "nodepool-launcher"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "zuul"
        app.kubernetes.io/part-of: "zuul"
        app.kubernetes.io/component: "nodepool-launcher"
    spec:
      initContainers:

        - name: "git-sync-init"
          image: "git-sync"
          args:
            - --depth=1
            - --link=current
            - --root=/git
            - --one-time
          env:
            - name: "GITSYNC_REPO"
              valueFrom:
                configMapKeyRef:
                  name: "zuul-instance-config"
                  key: "ZUUL_CONFIG_REPO"
          resources:
            limits:
              memory: "64Mi"
            requests:
              cpu: "10m"
              memory: "32Mi"

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true

          volumeMounts:
            - name: "zuul-config-data"
              mountPath: "/git"
            - name: "tmp"
              mountPath: "/tmp"
              subPath: "git-sync"

      containers:
        - name: "nodepool"
          image: "zuul/nodepool-launcher"
          command:
            - "/usr/local/bin/nodepool-launcher"
            - "-f"
            - "-d"
            - "-c"
            - "/data/current/nodepool/nodepool.yaml"

          resources:
            limits:
              memory: "500Mi"
            requests:
              cpu: "50m"
              memory: "200Mi"

          securityContext:
            runAsUser: 10001
            runAsGroup: 10001

          volumeMounts:
            - name: "zookeeper-client-tls"
              mountPath: "/tls/client"
              readOnly: true

            - name: "zuul-config-data"
              mountPath: "/data"
              readOnly: true

            - name: "nodepool-lib"
              mountPath: "/var/lib/nodepool"

        - name: "git-sync"
          image: "git-sync"
          args:
            - --depth=1
            - --period=60s
            - --link=current
            - --root=/git
          env:
            - name: "GITSYNC_REPO"
              valueFrom:
                configMapKeyRef:
                  name: "zuul-instance-config"
                  key: "ZUUL_CONFIG_REPO"
          resources:
            limits:
              memory: "64Mi"
            requests:
              cpu: "10m"
              memory: "32Mi"

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true

          volumeMounts:
            - name: "zuul-config-data"
              mountPath: "/git"
            - name: "tmp"
              mountPath: "/tmp"
              subPath: "git-sync"

      serviceAccountName: "zuul"
      volumes:
        - name: "nodepool-config"
          secret:
            secretName: "nodepool-config"

        - name: "zookeeper-client-tls"
          secret:
            secretName: "zookeeper-client-tls"

        - name: "zuul-config-data"
          emptyDir: {}

        - name: "nodepool-lib"
          emptyDir: {}

        - name: "tmp"
          emptyDir: {}
  revisionHistoryLimit: 2
