---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: defectdojo

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: main

helmCharts:
  - name: defectdojo
    repo: "https://raw.githubusercontent.com/DefectDojo/django-DefectDojo/helm-charts"
    version: "1.6.144"
    releasename: "main"
    namespace: "defectdojo"
    valuesFile: "helm-values.yaml"
    apiVersions:
      - networking.k8s.io/v1/Ingress
      - policy/v1

patches:
  # Patching unflexible bitnami redis chart
  - patch: |-
      - op: replace
        path: /apiVersion
        value: policy/v1
    target:
      kind: PodDisruptionBudget
      group: policy
      version: v1beta1
  - patch: |-
      - op: replace
        path: /metadata/name
        value: initializer-v1-6-144
    target:
      kind: Job
      group: batch
      version: v1
      labelSelector: "defectdojo.org/component=initializer"

resources:
  - namespace.yaml
  - pgsql-cloudnative.yaml
