---
image: "Debian 12"
flavor: "1C-4GB-20GB"
security_groups: ["default", "vault"]
nics:
  - fixed_ip: "10.6.0.31"
    net-name: "KG-Net-Fra"
#root_volume_size: 20
auto_ip: false

data_volumes:
  - name: "var"
    size: 25
  - name: "home"
    size: 5
  - name: "opt"
    size: 20

userdata: |
  #cloud-config
  disk_setup:
    /dev/vdb:
      table_type: 'mbr'
      layout:
        - 100
  fs_setup:
    - label: var
      filesystem: ext4
      device: '/dev/vdb3'
    - label: opt
      filesystem: ext4
      device: '/dev/vdb2'
    - label: home
      filesystem: ext4
      device: '/dev/vdb1'
  mounts:
    - [ "LABEL=home", "/home", "auto", "defaults", "0", "2" ]
  groups:
    - automation
  users:
    - default
    - name: automation
      primary_group: automation
      ssh_authorized_keys:
        - "{{ ssh_public_key }}"
      sudo: ALL=(ALL) NOPASSWD:ALL
  runcmd:
    - mkdir /mnt/vdb && mount /dev/vdb3 /mnt/vdb
    - cp -a /var/* /mnt/vdb/
    - umount /mnt/vdb && rmdir /mnt/vdb
    - echo "LABEL=var   /var   auto   defaults,comment=cloudconfig  0 2" >> /etc/fstab
    - echo "LABEL=opt   /opt   auto   defaults  0 2" >> /etc/fstab
    - mount /var
    - mkdir -p /opt
    - mount /opt

ssl_certs:
  vault:
    - "vault.infra.sovereignit.cloud"
    - "vault1.infra.sovereignit.cloud"
vault_cert: "vault"

firewalld_extra_ports_enable: ['8200/tcp', '8201/tcp']
