---
all:
  hosts:
    vault1.infra.sovereignit.cloud:
      ansible_host: 89.46.80.90
      ansible_user: automation
      location:
        cloud: "cn-fra1"
        ansible_host: "10.6.0.31"
        # az: "nova"
vault:
  hosts:
    vault1.infra.sovereignit.cloud:
ssl_certs:
  hosts:
    vault1.infra.sovereignit.cloud:
#    localhost:
#cloud_launcher:
#  hosts:
#    localhost:
