---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-scheduler
  labels:
    app.kubernetes.io/name: "zuul"
    app.kubernetes.io/part-of: "zuul"
    app.kubernetes.io/component: "zuul-scheduler"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "zuul"
      app.kubernetes.io/part-of: "zuul"
      app.kubernetes.io/component: "zuul-scheduler"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "zuul"
        app.kubernetes.io/part-of: "zuul"
        app.kubernetes.io/component: "zuul-scheduler"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/name"
                      operator: In
                      values:
                        - "zuul"
                    - key: "app.kubernetes.io/component"
                      operator: In
                      values:
                        - "zuul-scheduler"
                topologyKey: "kubernetes.io/hostname"

      initContainers:

        - name: "git-sync-init"
          image: "git-sync"
          args:
            - --depth=1
            - --link=current
            - --root=/git
            - --one-time
          env:
            - name: "GITSYNC_REPO"
              valueFrom:
                configMapKeyRef:
                  name: "zuul-instance-config"
                  key: "ZUUL_CONFIG_REPO"
          resources:
            limits:
              memory: "64Mi"
            requests:
              cpu: "10m"
              memory: "32Mi"

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true

          volumeMounts:
            - name: "zuul-config-data"
              mountPath: "/git"
            - name: "tmp"
              mountPath: "/tmp"
              subPath: "git-sync"


      containers:
        - name: "zuul"
          image: "zuul/zuul-scheduler"
          args: ["/usr/local/bin/zuul-scheduler", "-f", "-d"]

          ports:
            - containerPort: 9091
              name: "prometheus"
              protocol: "TCP"

          readinessProbe:
            httpGet:
              path: "/health/ready"
              port: "prometheus"
            failureThreshold: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: "/health/live"
              port: "prometheus"
            initialDelaySeconds: 120
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5

          resources:
            limits:
              memory: "2048Mi"
            requests:
              cpu: "100m"
              memory: "2048Mi"

          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true

          volumeMounts:
            - name: "zuul-config"
              mountPath: "/etc/zuul"
              readOnly: true
            - name: "zookeeper-client-tls"
              mountPath: "/tls/client"
              readOnly: true
            - name: "zuul-config-data"
              mountPath: "/etc/zuul-config"
              readOnly: true
            - name: "zuul-var-lib"
              mountPath: "/var/lib/zuul"
            - name: "zuul-var-run"
              mountPath: "/var/run/zuul"
            - name: "tmp"
              mountPath: "/tmp"
              subPath: "zuul"

        - name: "git-sync"
          image: "git-sync"
          args:
            - --depth=1
            - --period=60s
            - --link=current
            - --root=/git
          env:
            - name: "GITSYNC_REPO"
              valueFrom:
                configMapKeyRef:
                  name: "zuul-instance-config"
                  key: "ZUUL_CONFIG_REPO"
          resources:
            limits:
              memory: "64Mi"
            requests:
              cpu: "10m"
              memory: "32Mi"

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true

          volumeMounts:
            - name: "zuul-config-data"
              mountPath: "/git"
            - name: "tmp"
              mountPath: "/tmp"
              subPath: "git-sync"

      serviceAccountName: "zuul"
      volumes:
        - name: "zuul-config"
          secret:
            secretName: "zuul-config"

        - name: "zookeeper-client-tls"
          secret:
            secretName: "zookeeper-client-tls"

        - name: "zuul-config-data"
          emptyDir: {}

        - name: "zuul-var-lib"
          emptyDir: {}

        - name: "zuul-var-run"
          emptyDir: {}

        - name: "tmp"
          emptyDir: {}
