apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dependencytrack-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: dependencytrack-api
  serviceName: "dependencytrack-api"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: dependencytrack-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics

    spec:
      serviceAccount: dependency-track
      securityContext:
        fsGroup: 1000

      terminationGracePeriodSeconds: 10
      containers:
        - name: api
          image: dependencytrack/apiserver
          env:
            - name: ALPINE_METRICS_ENABLED
              value: "true"

          envFrom:
            - configMapRef:
                name: dependencytrack-api-config

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault

          resources:
            limits:
              cpu: "4"
              memory: 5Gi
            requests:
              cpu: "1"
              memory: 5Gi

          ports:
            - name: web
              containerPort: 8080
              protocol: TCP

          volumeMounts:
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp

          livenessProbe:
            httpGet:
              scheme: HTTP
              port: web
              path: /health/live
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              scheme: HTTP
              port: web
              path: /health/ready
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5

      volumes:
        - name: dependencytrack-api-config
          configMap:
            defaultMode: 420
            name: dependencytrack-api-config

        - name: tmp
          emptyDir: { }

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
