- name: Generate list of changed certificates
  set_fact:
    acme_txt_changed: '{{ acme_txt_required|map("first")|list|unique }}'

- name: Include ACME validation
  include_tasks: acme.yaml
  loop: "{{ query('dict', ssl_certs) }}"
  loop_control:
    loop_var: cert
  when:
    - "ssl_certs is defined"
    # - item.key in acme_txt_changed

- name: Create haproxy certs directory
  ansible.builtin.file:
    path: "/etc/ssl/{{ inventory_hostname }}/haproxy"
    state: "directory"
    mode: "0755"

- name: Check vault user
  ansible.builtin.user:
    name: "vault"
  register: "vault_user"
  when: "'vault' in group_names"

- name: Create vault certs directory
  ansible.builtin.file:
    path: "/etc/ssl/{{ inventory_hostname }}/vault"
    state: "directory"
    mode: "0755"
    owner: "{{ vault_user.name | default(omit) }}"
    group: "{{ vault_user.group | default(omit) }}"
  when: "'vault' in group_names"

- name: Copy vault certs
  ansible.builtin.copy:
    src: "{{ certs_path }}/{{ cert }}"
    dest: "{{ certs_path }}/vault/{{ cert }}"
    mode: "0440"
    owner: "{{ vault_user.name | default(omit) }}"
    group: "{{ vault_user.group | default(omit) }}"
    remote_src: true
  loop:
    - "{{ vault_cert }}.pem"
    - "{{ vault_cert }}-fullchain.crt"
  loop_control:
    loop_var: "cert"
  notify:
    - Reload vault
  when:
    - "'vault' in group_names"
    - "vault_cert is defined"
