---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-client
  labels:
    app.kubernetes.io/name: "zuul"
    app.kubernetes.io/component: "zuul-client"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "zuul"
      app.kubernetes.io/component: "zuul-client"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "zuul"
        app.kubernetes.io/component: "zuul-client"
    spec:
      serviceAccountName: "zuul"

      initContainers:

        - name: "git-sync-init"
          image: "git-sync"
          args:
            - --depth=1
            - --link=current
            - --root=/git
            - --one-time
          env:
            - name: "GITSYNC_REPO"
              valueFrom:
                configMapKeyRef:
                  name: "zuul-instance-config"
                  key: "ZUUL_CONFIG_REPO"
          resources:
            limits:
              memory: "64Mi"
            requests:
              cpu: "10m"
              memory: "32Mi"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true

          volumeMounts:
            - name: "zuul-config-data"
              mountPath: "/git"
            - name: "tmp"
              mountPath: "/tmp"
              subPath: "git-sync"

      containers:
        # Zuul-client is a regular zuul-web image doing nothing.
        # We use it only to have completely independent pod serving as
        # zuul client for i.e. maintenance.
        - name: "zuul"
          image: "zuul/zuul-web"
          command:
            - "sh"
            - "-c"
            - "while :; do sleep 60; done"

          resources:
            limits:
              memory: "256Mi"
            requests:
              cpu: "10m"
              memory: "128Mi"

          securityContext:
            runAsUser: 10001
            runAsGroup: 10001

          volumeMounts:
            - name: "zuul-config"
              mountPath: "/etc/zuul"
              readOnly: true
            - name: "zookeeper-client-tls"
              mountPath: "/tls/client"
              readOnly: true
            - name: "zuul-config-data"
              mountPath: "/etc/zuul-config"
              readOnly: true

        - name: "git-sync"
          image: "git-sync"
          args:
            - --depth=1
            - --period=60s
            - --link=current
            - --root=/git
          env:
            - name: "GITSYNC_REPO"
              valueFrom:
                configMapKeyRef:
                  name: "zuul-instance-config"
                  key: "ZUUL_CONFIG_REPO"
          resources:
            limits:
              memory: "64Mi"
            requests:
              cpu: "10m"
              memory: "32Mi"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true

          volumeMounts:
            - name: "zuul-config-data"
              mountPath: "/git"
            - name: "tmp"
              mountPath: "/tmp"
              subPath: "git-sync"

      volumes:
        - name: "zuul-config"
          secret:
            secretName: "zuul-config"

        - name: "zookeeper-client-tls"
          secret:
            secretName: "zookeeper-client-tls"

        - name: "zuul-config-data"
          emptyDir: {}

        - name: "tmp"
          emptyDir: {}
  revisionHistoryLimit: 2
