---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: prod

namespace: dependencytrack

patches:
  - patch: |-
      - op: replace
        path: /spec/ingressClassName
        value:
          nginx
      - op: replace
        path: /spec/rules/0/host
        value:
          dependencytrack.infra.sovereignit.cloud
      - op: replace
        path: /metadata/annotations
        value:
          nginx.ingress.kubernetes.io/proxy-body-size: "50m"
          cert-manager.io/cluster-issuer: letsencrypt-prod
      - op: replace
        path: /spec/tls
        value:
          - hosts:
              - dependencytrack.infra.sovereignit.cloud
            secretName: dependencytrack-cert-prod
    target:
      group: networking.k8s.io
      kind: Ingress
      name: dependencytrack
      version: v1

  - patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value:
          "csi-cinder-sc-delete"
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value:
          "5G"
    target:
      group: apps
      kind: StatefulSet
      name: dependencytrack-api
      version: v1

  - path: api-patch.yaml

configMapGenerator:
  - behavior: "replace"
    envs:
      - dependencytrack.env
    name: dependencytrack-config
  - behavior: "replace"
    envs:
      - dependencytrack-api.env
    name: dependencytrack-api-config

resources:
  - ../../base
  - namespace.yaml
  - pgsql-cloudnative.yaml
  #  - sa.yaml
