---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: goncharov@osb-alliance.com
    privateKeySecretRef:
      name: letsencrypt-prodr-account-key
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
