---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "backup-zuul"
  labels:
    app.kubernetes.io/name: "zuul"
    app.kubernetes.io/component: "zuul-backup"
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  schedule: '0 0 * * *'
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: "zuul"
          restartPolicy: "Never"
          containers:
            - name: "zuul"
              image: "zuul/zuul-web"
              command:
                - "/bin/sh"
                - "-ec"
              args:
                - "zuul-admin export-keys /tmp/backup/zuul-keys-$(date +%Y%m%d)"
              volumeMounts:
                - mountPath: "/tmp/backup"
                  name: "backup"
                - name: "zuul-config"
                  mountPath: "/etc/zuul"
                  readOnly: true
                - name: "zookeeper-client-tls"
                  mountPath: "/tls/client"
                  readOnly: true

            - name: "upload"
              image: "ghcr.io/gtema/openstack"
              command:
                - "/bin/sh"
                - "-c"
              args:
                - "sleep 20 && cd /tmp/backup && for file in $(find . -type f); do cat $file | osc --os-cloud backup object-store object upload backup zuul/${file#./} -vv; done"
              volumeMounts:
                - mountPath: "/tmp/backup"
                  name: "backup"
                - mountPath: "/etc/openstack"
                  name: "zuul-config"
                  subPath: "openstack"

          initContainers:
            - name: "vault-agent-init"
              args:
                - touch /home/vault/.vault-token && bao agent -config=/vault/configs/config-zuul-backup.hcl -exit-after-auth=true
              command:
                - "/bin/sh"
                - "-ec"
              env:
                - name: "VAULT_ADDR"
                  value: "https://vault.infra.sovereignit.cloud:8200"
                - name: "VAULT_LOG_LEVEL"
                  value: "debug"
                - name: "VAULT_LOG_FORMAT"
                  value: "standard"
              image: "hashicorp/vault"
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
                runAsGroup: 10001
                runAsNonRoot: true
                runAsUser: 10001
              resources:
                limits:
                  memory: "256Mi"
                requests:
                  cpu: "5m"
                  memory: "32Mi"
              volumeMounts:
                - mountPath: "/home/vault"
                  name: "home-init"
                - mountPath: "/var/run/secrets/kubernetes.io/serviceaccount"
                  name: "kube-api-access"
                  readOnly: true
                - mountPath: "/vault/secrets"
                  name: "zuul-config"
                - mountPath: "/vault/custom"
                  name: "extra-secrets"
                  readOnly: true
                - mountPath: "/vault/configs"
                  name: "vault-config"
                  readOnly: true
                - mountPath: "/vault/db-secrets"
                  name: "db-secrets"
                  readOnly: true

          volumes:
            - name: "backup"
              emptyDir:
                medium: "Memory"
            - name: "zuul-config"
              emptyDir:
                medium: "Memory"
            - name: "kube-api-access"
              projected:
                defaultMode: 420
                sources:
                  - serviceAccountToken:
                      expirationSeconds: 7200
                      path: "token"
                  - configMap:
                      items:
                        - key: "ca.crt"
                          path: "ca.crt"
                      name: "kube-root-ca.crt"
                  - downwardAPI:
                      items:
                        - fieldRef:
                            apiVersion: "v1"
                            fieldPath: "metadata.namespace"
                          path: "namespace"
            - name: "home-init"
              emptyDir:
                medium: "Memory"
            - name: "home-sidecar"
              emptyDir:
                medium: "Memory"
            - name: "zookeeper-client-tls"
              secret:
                secretName: "zookeeper-client-tls"
            - name: "vault-config"
              configMap:
                name: "vault-agent-config"
            - name: "extra-secrets"
              secret:
                defaultMode: 420
                secretName: "vault-backup-config"
            - name: "db-secrets"
              secret:
                secretName: "zuul-db-app"
