---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nodepool-builder
  labels:
    app.kubernetes.io/name: "zuul"
    app.kubernetes.io/part-of: "zuul"
    app.kubernetes.io/component: "nodepool-builder"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "zuul"
      app.kubernetes.io/part-of: "zuul"
      app.kubernetes.io/component: "nodepool-builder"
  serviceName: "nodepool-builder"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "zuul"
        app.kubernetes.io/part-of: "zuul"
        app.kubernetes.io/component: "nodepool-builder"
    spec:
      initContainers:

        - name: "git-sync-init"
          image: "git-sync"
          args:
            - --depth=1
            - --link=current
            - --root=/git
            - --one-time
          env:
            - name: "GITSYNC_REPO"
              valueFrom:
                configMapKeyRef:
                  name: "zuul-instance-config"
                  key: "ZUUL_CONFIG_REPO"
          resources:
            limits:
              memory: "64Mi"
            requests:
              cpu: "10m"
              memory: "32Mi"

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true

          volumeMounts:
            - name: "zuul-config-data"
              mountPath: "/git"
            - name: "tmp"
              mountPath: "/tmp"
              subPath: "git-sync"

      containers:
        - name: "nodepool"
          image: "zuul/nodepool-builder"
          command:
            - "/usr/local/bin/nodepool-builder"
            - "-f"
            - "-d"
            - "-c"
            - "/data/current/nodepool/nodepool.yaml"

          resources:
            limits:
              memory: "2048Mi"
            requests:
              cpu: "300m"
              memory: "1024Mi"

          securityContext:
            privileged: true
            # runAsUser: 10001
            # runAsGroup: 10001

          volumeMounts:
            - name: "dev"
              mountPath: "/dev"

            - name: "dib-tmp"
              mountPath: "/opt/dib_tmp"

            - name: "dib-cache"
              mountPath: "/opt/dib_cache"

            - name: "nodepool-images-dir"
              mountPath: "/opt/nodepool/images"

            # Podman need non-overlayfs
            - name: "nodepool-containers"
              mountPath: "/var/lib/containers"

            - name: "zookeeper-client-tls"
              mountPath: "/tls/client"
              readOnly: true

            - name: "zuul-config-data"
              mountPath: "/data"
              readOnly: true

        - name: "git-sync"
          image: "git-sync"
          args:
            - --depth=1
            - --period=60s
            - --link=current
            - --root=/git
          env:
            - name: "GITSYNC_REPO"
              valueFrom:
                configMapKeyRef:
                  name: "zuul-instance-config"
                  key: "ZUUL_CONFIG_REPO"
          resources:
            limits:
              memory: "64Mi"
            requests:
              cpu: "10m"
              memory: "32Mi"

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true

          volumeMounts:
            - name: "zuul-config-data"
              mountPath: "/git"
            - name: "tmp"
              mountPath: "/tmp"
              subPath: "git-sync"

      serviceAccountName: "zuul"
      volumes:
        - name: "nodepool-config"
          secret:
            secretName: "nodepool-config"

        - name: "dev"
          hostPath:
            path: "/dev"

        - name: "dib-cache"
          emptyDir: {}

        - name: "dib-tmp"
          emptyDir: {}

        - name: "nodepool-containers"
          emptyDir: {}

        - name: "zookeeper-client-tls"
          secret:
            secretName: "zookeeper-client-tls"

        - name: "zuul-config-data"
          emptyDir: {}

        - name: "tmp"
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: "nodepool-images-dir"
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "80G"
