---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../components/ca
  - ../components/zookeeper
  - ../components/zuul-executor
  #- ../components/zuul-merger
  - ../components/zuul-scheduler
  - ../components/zuul-web
  - ../components/nodepool-launcher

configMapGenerator:
  - name: "zuul-instance-config"
    literals:
      - ZUUL_CONFIG_REPO=https://github.com/sovereigncloudstack/zuul-config.git
  - name: "zuul-executor-vars"
    literals: []

images:
  - name: "git-sync"
    newName: "gcr.io/k8s-staging-git-sync/git-sync"
    newTag: "v4.2.3"

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: "base"
      app.kubernetes.io/managed-by: "kustomize"

resources:
  - sa.yaml
  - cert.yaml

secretGenerator:
  - name: "zuul-config"
    files:
      - "configs/zuul.conf"
  - name: "nodepool-config"
    files: []
