---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zuul-ci

components:
  - ../../components/zuul-client
  - ../../components/zuul-merger
  - ../../components/nodepool-builder
  - ../../components/zuul-backup

configMapGenerator:
  - name: "vault-agent-config"
    files:
      - "config-zuul.hcl=configs/vault-agent/config-zuul.hcl"
      - "config-zuul-backup.hcl=configs/vault-agent/config-zuul-backup.hcl"
      - "config-nodepool.hcl=configs/vault-agent/config-nodepool.hcl"
      - "executor-base-vault-agent.hcl=configs/vault-agent/executor-base-vault-agent.hcl"
  - name: "zuul-instance-config"
    behavior: "replace"
    literals:
      - ZUUL_CONFIG_REPO=https://github.com/sovereigncloudstack/zuul-config.git
  - name: "zuul-executor-vars"
    behavior: "replace"
    files:
      - "configs/site-vars.yaml"

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: zuul-ci

images:
  - name: "busybox"
    newName: "quay.io/prometheus/busybox"
    newTag: "latest"

  - name: "git-sync"
    newName: "registry.k8s.io/git-sync/git-sync"
    newTag: "v4.2.4@sha256:827729ef28026c3aa73aecde6d1757a2e6967996cc64de43b39cf101ac28a9d1"

  - name: "ghcr.io/gtema/openstack"
    newTag: "0.6.4@sha256:1fcf0f6268dacd2b0934e7fe1395032d3abc4168895a6ebf9286657d64d6e1ae"

  - name: "hashicorp/vault"
    newName: "quay.io/openbao/openbao"
    newTag: "2.0.0@sha256:5eedbca9922d85eca5e4bc68c11f968d245b4046641dd4173c1dcff7ae7091aa"

  - name: "zuul/zuul-executor"
    newName: "quay.io/zuul-ci/zuul-executor"
    newTag: "11.2.0"

  - name: "zuul/zuul-merger"
    newName: "quay.io/zuul-ci/zuul-merger"
    newTag: "11.2.0"

  - name: "zuul/zuul-scheduler"
    newName: "quay.io/zuul-ci/zuul-scheduler"
    newTag: "11.2.0"

  - name: "zuul/zuul-web"
    newName: "quay.io/zuul-ci/zuul-web"
    newTag: "11.2.0"

  - name: "zuul/nodepool-builder"
    newName: "quay.io/zuul-ci/nodepool-builder"
    newTag: "11.0.0"

  - name: "zuul/nodepool-launcher"
    newName: "quay.io/zuul-ci/nodepool-launcher"
    newTag: "11.0.0"


patches:
  # Patch zookeeper (storage class, size and count)
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3

      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: "csi-cinder-sc-delete"

      - op: add
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: "5Gi"
    target:
      group: apps
      kind: StatefulSet
      name: zookeeper
      version: v1

  # Path zuul components (replace config and enable vault)
  - patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0
        value:
          name: "zuul-config"
          emptyDir:
            medium: "Memory"
    target:
      labelSelector: "app.kubernetes.io/name=zuul,app.kubernetes.io/component in (zuul-scheduler,zuul-executor,zuul-merger,zuul-web,zuul-client)"
      group: apps
      version: v1

  - path: patch-zuul.yaml
    target:
      labelSelector: "app.kubernetes.io/name=zuul,app.kubernetes.io/component in (zuul-scheduler,zuul-executor,zuul-merger,zuul-web,zuul-client)"
      group: apps
      version: v1

      ## Patching zuul-executor count
      #- patch: |-
      #    - op: replace
      #      path: /spec/replicas
      #      value: 1
      #  target:
      #    labelSelector: "app.kubernetes.io/name=zuul,app.kubernetes.io/component=zuul-executor"
      #    group: apps
      #    version: v1

  # Add zuul-executor base job vault token
  - path: patch-zuul-executor.yaml
    target:
      labelSelector: "app.kubernetes.io/name=zuul,app.kubernetes.io/component=zuul-executor"
      group: apps
      version: v1

  # Patching Nodepool components (replace config and enable vault)
  - patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0
        value:
          name: "nodepool-config"
          emptyDir: {}
    target:
      labelSelector: "app.kubernetes.io/name=zuul,app.kubernetes.io/component in (nodepool-launcher,nodepool-builder)"
      group: apps
      version: v1

  # Set storageClassName for nodepool-builder
  - patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: "csi-cinder-sc-delete"
    target:
      labelSelector: "app.kubernetes.io/name=zuul,app.kubernetes.io/component=nodepool-builder"
      group: apps
      version: v1

  - path: patch-nodepool.yaml
    target:
      labelSelector: "app.kubernetes.io/name=zuul,app.kubernetes.io/component in (nodepool-launcher,nodepool-builder)"
      group: apps
      version: v1

  # Patching web
  - patch: |-
      - op: replace
        path: /spec/ingressClassName
        value: nginx
      - op: replace
        path: /spec/rules/0/host
        value: zuul.sovereignit.cloud
      - op: replace
        path: /metadata/annotations
        value:
          cert-manager.io/cluster-issuer: letsencrypt-prod
      - op: replace
        path: /spec/tls
        value:
          - hosts:
              - zuul.sovereignit.cloud
            secretName: zuul-cert-prod
    target:
      group: networking.k8s.io
      kind: Ingress
      name: zuul-web
      version: v1

resources:
  - pgsql-cloudnative.yaml
  - ../../base
  - crb.yaml
  - crb_admin.yaml

secretGenerator:
  # Replacing general secrets to be able to trigger updates
  - name: zuul-config
    behavior: "replace"
    files:
      - "configs/zuul.conf.hcl"
  - name: nodepool-config
    behavior: "replace"
    files:
      - "configs/openstack/clouds.yaml.hcl"
  - name: vault-backup-config
    files:
      - "configs/zuul.conf.hcl"
      - "configs/openstack/clouds-backup.yaml.hcl"
  # Vault configs
  - name: vault-config-zuul
    files:
      - "configs/zuul.conf.hcl"
  - name: vault-config-nodepool
    files:
      - "configs/openstack/clouds.yaml.hcl"
      - "configs/kube.config.hcl"
