---
# Add HashiCorp Vault agent sidecars to render Zuul config
apiVersion: batch/v1
kind: not-used
metadata:
  name: not-used
spec:
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: "vault-agent-init"
              args:
                - touch /home/vault/.vault-token && bao agent -config=/vault/configs/config-zuul.hcl -exit-after-auth=true
              command:
                - "/bin/sh"
                - "-ec"
              env:
                - name: "VAULT_ADDR"
                  value: "https://vault.infra.sovereignit.cloud:8200"
                - name: "VAULT_LOG_LEVEL"
                  value: "debug"
                - name: "VAULT_LOG_FORMAT"
                  value: "standard"
              image: "hashicorp/vault"
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
                runAsGroup: 10001
                runAsNonRoot: true
                runAsUser: 10001
              resources:
                limits:
                  memory: "256Mi"
                requests:
                  cpu: "5m"
                  memory: "32Mi"
              volumeMounts:
                - mountPath: "/home/vault"
                  name: "home-init"
                - mountPath: "/var/run/secrets/kubernetes.io/serviceaccount"
                  name: "kube-api-access"
                  readOnly: true
                - mountPath: "/vault/secrets"
                  name: "zuul-config"
                - mountPath: "/vault/custom"
                  name: "extra-secrets"
                  readOnly: true
                - mountPath: "/vault/configs"
                  name: "vault-config"
                  readOnly: true
                - mountPath: "/vault/db-secrets"
                  name: "db-secrets"
                  readOnly: true

          volumes:
            - name: "kube-api-access"
              projected:
                defaultMode: 420
                sources:
                  - serviceAccountToken:
                      expirationSeconds: 7200
                      path: "token"
                  - configMap:
                      items:
                        - key: "ca.crt"
                          path: "ca.crt"
                      name: "kube-root-ca.crt"
                  - downwardAPI:
                      items:
                        - fieldRef:
                            apiVersion: "v1"
                            fieldPath: "metadata.namespace"
                          path: "namespace"
            - name: "home-init"
              emptyDir:
                medium: "Memory"
            - name: "home-sidecar"
              emptyDir:
                medium: "Memory"
            - name: "vault-config"
              configMap:
                name: "vault-agent-config"
            - name: "extra-secrets"
              secret:
                defaultMode: 420
                secretName: "vault-config-zuul"
            - name: "db-secrets"
              secret:
                secretName: "zuul-db-app"
