- name: Check vault process
  command: pgrep -f openbao
  ignore_errors: yes
  register: vault_pids

- name: Reload Vault
  ansible.builtin.service:
    name: "openbao"
    state: "reloaded"
  when: vault_pids.rc == 0
