---
# Provision VM for Vault
- name: "Provision VM for Vault"
  hosts: "localhost"
  vars:
    group: "vault"
  tasks:
   - name: "Manage OpenStack hosts"
     include_role:
       name: "cloud_host"
     loop: "{{ groups[group] }}"
     loop_control:
       loop_var: "host"
     when:
       - "hostvars[host].location is defined"
       - "hostvars[host]['location']['cloud'] is defined"
       - "limit_host is defined and limit_host == host or limit_host is not defined"


